version: "3.9"

services:
  nginx:
    container_name: "nginx"
    build: ./src/requirements/nginx
    restart: unless-stopped
    env_file:
      - ./src/.env
    networks:
      - inceptionNetwork
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_volume:/var/www/wp_site

volumes:
  wp_volume:
    name: "wp_volume"
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/data/wp_site"

networks:
  inceptionNetwork:
    name: "inceptionNetwork"
    driver: "bridge"
