version: "3.9"

services:
  nginx:
    container_name: "nginx"
    build: ./requirements/nginx
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inceptionNetwork
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/wp_site
    depends_on:
      - wordpress

  wordpress:
    container_name: "wordpress"
    build: ./requirements/wordpress
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inceptionNetwork
    volumes:
      - wp_volume:/var/www/wp_site
    depends_on:
      - mariadb

  mariadb:
    container_name: "mariadb"
    build: ./requirements/mariadb
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inceptionNetwork
    volumes:
      - db_volume:/var/lib/mysql

  adminer:
    container_name: "adminer"
    build: ./requirements/bonus/adminer
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inceptionNetwork
    depends_on:
      - mariadb

  website:
    container_name: "website"
    build: ./requirements/bonus/website
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inceptionNetwork

  redis:
    container_name: "redis"
    build: ./requirements/bonus/redis
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inceptionNetwork

  ftp:
    container_name: "ftp"
    build: ./requirements/bonus/ftp
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inceptionFtpNetwork
    volumes:
      - wp_volume:/var/www/wp_site
    ports:
      - "20-21:20-21"
      - "5000-5100:5000-5100"

volumes:
  wp_volume:
    name: "wp_volume"
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/data/wp_site"

  db_volume:
    name: "db_volume"
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/data/mariadb"

networks:
  inceptionNetwork:
    name: "inceptionNetwork"
    driver: "bridge"
  inceptionFtpNetwork:
    name: "inceptionFtpNetwork"
    driver: "bridge"
